### PR TITLE
more cleanup

### PR DESCRIPTION
**Pull request by valkyrienyanko**

### CODE REVIEW

**Comment by system-er** [comment]
thank you very much for the work. please excuse, but i think if a code is working, use the old proven rule - never change a running system. cleanup is like cosmetics. whats your opion?

**Comment by valkyrienyanko** [comment]
if you're not going to read code in future then don't pr this otherwise I mean it's totally up to you on what to do

**Comment by system-er** [comment]
nice to meet you, how is the weather in canada? sry, im new to github, whats the meaning of "pr"? ok, i will read your recommendations, thank you.

**Comment by valkyrienyanko** [comment]
Weather is nice in Canada right now

PR means Pull Request

**Comment by valkyrienyanko** [comment]
I have resolved the conflicts this pull request had.

**Comment by system-er** [comment]
ah, Pull Request, thank you.

**Comment by system-er** [comment]
is now everything merged??

**Comment by system-er** [comment]
now i have hundreds of errors and nothing works. have you tested your changes before?? should i restore older source-version?

**Comment by system-er** [comment]
i test with godot 4.1

**Comment by valkyrienyanko** [comment]
I don't know what I could have done wrong. Just forget about this PR then.

**Comment by system-er** [comment]
but have you tested and do you get the errors, too? or should i click on the "revert" button?

**Comment by valkyrienyanko** [comment]
I did not test it as I assumed it would work. I am sorry for the inconvenience this has caused you. Click the revert button.

**Comment by system-er** [comment]
ok, i found the button this afternoon :-) thank you, please test next time. no problem. its cool that you contribute.

**Pull request merged**
